fix bug in favorite create endpoint
fix bug in favorite create endpoint,
an error "    return Favorite.objects.create(user=user, product=product, ** validated_data)
NameError: name 'productو' is not defined"
and that was due to conflict in names , so i renamed the product variable to _product